- alias: Turn on garden lights when sun sets
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
  action:
    service: switch.turn_on
    entity_id: switch.garden_lights

- alias: Turn off garden lights when sun rises
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunrise
  action:
    service: switch.turn_off
    entity_id: switch.garden_lights

- alias: Turn on window lights 30min before sunset
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  action:
    service: switch.turn_on
    entity_id: group.window_lights

- alias: Turn off indoor lights at night
  initial_state: True
  hide_entity: False
  trigger:
    platform: time
    at: '22:30:00'
  action:
    service: switch.turn_off
    entity_id: group.indoor_lights

- alias: Turn on garage lights when sun sets
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    entity_id: light.garage

- alias: Turn off garage lights when sun rises
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id: light.garage
