- id: auto1
  alias: Turn on garden lights when sun sets
  initial_state: true
  hide_entity: false
  trigger:
    platform: sun
    event: sunset
  action:
    service: switch.turn_on
    entity_id: switch.garden_lights
- id: auto2
  alias: Turn off garden lights when sun rises
  initial_state: true
  hide_entity: false
  trigger:
  - event: sunrise
    platform: sun
  action:
    service: switch.turn_off
    data:
      entity_id: switch.garden_lights
- id: auto3
  alias: Turn on downstairs window lights at sunset
  initial_state: true
  hide_entity: false
  trigger:
  - event: sunset
    offset: 00:05
    platform: sun
  action:
  - data:
      entity_id: switch.window_lights_downstairs
    service: switch.turn_on
- id: auto4
  alias: Turn off indoor lights at night
  initial_state: true
  hide_entity: false
  trigger:
  - at: '22:30:00'
    platform: time
  action:
    service: switch.turn_off
    data:
      entity_id: group.indoor_lights
- id: auto5
  alias: Turn on garage lights when sun sets
  initial_state: true
  hide_entity: false
  trigger:
  - event: sunset
    offset: 00:25:00
    platform: sun
  action:
  - data:
      brightness: 190
      entity_id: light.garage
    service: light.turn_on
- id: auto6
  alias: Turn on outdoor ceiling lights when sun sets
  initial_state: true
  hide_entity: false
  trigger:
  - event: sunset
    offset: 00:20:00
    platform: sun
  action:
  - data:
      entity_id: light.outdoor_ceiling
    service: light.turn_on
- id: auto7
  alias: Turn off garage lights when sun rises
  initial_state: true
  hide_entity: false
  trigger:
  - event: sunrise
    platform: sun
  action:
  - data:
      entity_id: light.garage
    service: light.turn_off
- id: auto8
  alias: Turn off outdoor ceiling lights when sun rises
  initial_state: true
  hide_entity: false
  trigger:
  - event: sunrise
    offset: -01:10:00
    platform: sun
  action:
  - data:
      entity_id: light.outdoor_ceiling
    service: light.turn_off
- id: auto9
  alias: Notify Lars when door is opened
  trigger:
    platform: state
    entity_id: sensor.front_door_opened
  condition:
    condition: state
    entity_id: device_tracker.larsiphone
    state: not_home
  action:
    service: notify.ios_larsiphone
    data:
      message: The front door has been opened!
      data:
        push:
          sound: US-EN-Alexa-Front-Door-Opened.wav
- id: '1511102616915'
  alias: Turn on upstairs window lights at night
  trigger:
  - event: sunset
    offset: 00:00:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.window_lights_upstairs
    service: switch.turn_on
