- id: auto1
  alias: Turn on garden lights when sun sets
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
  action:
    service: switch.turn_on
    entity_id: switch.garden_lights

- id: auto2
  alias: Turn off garden lights when sun rises
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunrise
  action:
    service: switch.turn_off
    entity_id: switch.garden_lights

- id: auto3
  alias: Turn on window lights 30min before sunset
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  action:
    service: switch.turn_on
    entity_id: group.window_lights

- id: auto4
  alias: Turn off indoor lights at night
  initial_state: True
  hide_entity: False
  trigger:
    platform: time
    at: '22:30:00'
  action:
    service: switch.turn_off
    entity_id: group.indoor_lights

- id: auto5
  alias: Turn on garage lights when sun sets
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    entity_id: light.garage

- id: auto6
  alias: Turn on outdoor ceiling lights when sun sets
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
    offset: '00:10:00'
  action:
    service: light.turn_on
    entity_id: light.outdoor_ceiling

- id: auto7
  alias: Turn off garage lights when sun rises
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id: light.garage

- id: auto8
  alias: Turn off outdoor ceiling lights when sun rises
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunrise
    offset: '00:10:00'
  action:
    service: light.turn_off
    entity_id: light.outdoor_ceiling

- id: auto9
  alias: Notify Lars when door is opened
  trigger:
    platform: state
    entity_id: sensor.front_door_opened
  condition:
    condition: state
    entity_id: device_tracker.larsiphone
    state: not_home
  action:
    service: notify.ios_larsiphone
    data:
      message: The front door has been opened!
      data:
        push:
          sound: "US-EN-Alexa-Front-Door-Opened.wav"

