- alias: Turn on garden lights when sun sets
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
  action:
    service: switch.turn_on
    entity_id: switch.garden_lights

- alias: Turn off garden lights when sun rises
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunrise
  action:
    service: switch.turn_off
    entity_id: switch.garden_lights

- alias: Turn off indoor lights at night
  initial_state: True
  hide_entity: False
  trigger:
    platform: time
    after: '23:00:00'
  action:
    service: switch.turn_off
    entity_id: group.indoor_lights
