- platform: mjpeg
  mjpeg_url: http://192.168.1.19:8081
  name: outdoor1
  username: !secret motion_user
  password: !secret motion_pwd
- platform: mjpeg
  mjpeg_url: http://192.168.1.17:8081
  name: outdoor2
  username: !secret motion_user
  password: !secret motion_pwd
- platform: rpi_camera
  name: rpi
  timelapse: 1000
