homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 59.3333
  longitude: 18.05
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 11
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
#sun:

# Weather Prediction
#sensor yr:
#  - platform: yr

sensor: !include sensors.yaml

# Text to speech
#tts:
#  platform: google

mqtt:
  broker: 192.168.1.16
  port: 1883
  client_id: home-assistant-1
  keepalive: 60

panel_iframe:
  charts:
    title: 'Charts'
    url: 'http://192.168.1.16:6001/ChartData'
    icon: 'mdi:chart-line'

#device_tracker:
#  - platform: nmap_tracker
#    hosts: 192.168.1.108
#    home_interval: 5

switch: !include switches.yaml

camera: !include cameras.yaml

group: !include groups.yaml

