homeassistant:
  name: Our House
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 11
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customization.yaml

# Enables the frontend
frontend:

http:
  api_password: !secret ha_pwd
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

# Checks for available updates
updater:

logger:
  default: error

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor yr:
  - platform: yr
    name: Weather
    monitored_conditions:
        - temperature
        - symbol
        - precipitation
        - windSpeed
        - pressure
        - windDirection
        - humidity
        - fog
        - cloudiness
        - lowClouds
        - mediumClouds
        - highClouds
        - dewpointTemperature
        
sensor: !include sensors.yaml

mqtt:
  broker: 192.168.1.16
  port: 1883
  client_id: home-assistant-1
  keepalive: 60

panel_iframe:
  charts:
    title: 'Charts'
    url: 'http://192.168.1.16:6001/ChartData'
    icon: 'mdi:chart-line'

device_tracker: !include device_trackers.yaml

switch: !include switches.yaml

camera: !include cameras.yaml

group: !include groups.yaml

automation: !include automation.yaml

#zwave: !include zwave.yaml
#zwave:
#  usb_path: /dev/ttyAMA0