homeassistant:
  name: Our House
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 38
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customization.yaml

config:

tts:
  - platform: google
    language: 'sv'

map:

http:
  api_password: !secret ha_pwd
#  ssl_certificate: !secret ssl_certificate
#  ssl_key: !secret ssl_key

# purge db after 3 days. problems with sqlite
recorder:
  purge_interval: 1
  purge_keep_days: 3

# Sonos and Squeezebox
media_player: !include media_players.yaml

light:
  - platform: hue
    host: 192.168.1.232

# Checks for available updates
updater:

logger:
  default: error
  logs:
    homeassistant.components.media_player: critical

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Moon
sensor moon:
  - platform: moon

# Weather Prediction
sensor yr:
  - platform: yr
    name: yr
    monitored_conditions:
        - temperature
        - symbol
        - precipitation
        - windSpeed
        - pressure
        - windDirection
        - humidity
        - fog
        - cloudiness
        - lowClouds
        - mediumClouds
        - highClouds
        - dewpointTemperature
        
sensor: !include sensors.yaml

mqtt:
  broker: 192.168.1.17
  port: 1883
  client_id: home-assistant-1
  keepalive: 60

panel_iframe:
  charts:
    title: 'Charts'
    url: 'http://192.168.1.16:6001/ChartData'
    icon: 'mdi:chart-line'
  grafana:
    title: 'Grafana'
    url: http://192.168.1.16:3000/dashboard/db/sensordata_test?from=1498894609416&to=1498905409417
    icon: 'mdi:chart-areaspline'


device_tracker: !include device_trackers.yaml

switch: !include switches.yaml

camera: !include cameras.yaml

group: !include groups.yaml

automation: !include automations.yaml

discovery:

ios:

binary_sensor:
  - platform: mqtt
    name: "Back door open status"
    state_topic: "Home/Backdoor/Open"
    payload_on: "On"
    payload_off: "Off"
    qos: 0
    device_class: opening
    value_template: '{{ value.x }}'

