homeassistant:
  name: Our House
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 11
  unit_system: metric
  time_zone: Europe/Stockholm

# Enables the frontend
frontend:

http:
  api_password: !secret ha_pwd

# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor yr:
  - platform: yr

sensor: !include sensors.yaml

mqtt:
  broker: 192.168.1.16
  port: 1883
  client_id: home-assistant-1
  keepalive: 60

panel_iframe:
  charts:
    title: 'Charts'
    url: 'http://192.168.1.16:6001/ChartData'
    icon: 'mdi:chart-line'

#device_tracker:
#  - platform: nmap_tracker
#    hosts: 192.168.1.108
#    home_interval: 5

switch: !include switches.yaml

camera: !include cameras.yaml

group: !include groups.yaml

