#
# Groups that are views
#
default_view:
    view: yes
    entities:
        - group.groundfloor
        - group.topfloor
        - group.outdoor
        - group.weather_and_sun
        - group.family

garage:
    view: yes
    entities:
        - group.garage_group

cams:
    view: yes
    entities:
        - camera.outdoor
        - camera.rpi

automation:
    view: yes
    entities:
        - group.automation_garden_group
        - group.automation_indoor_group

#
# Groups that are not views
#
groundfloor:
    name: Ground floor
    entities:
        - switch.window_lights_downstairs
        - switch.wall_lights_downstairs
        - sensor.ground_floor_temp
        - sensor.ground_floor_humidity

topfloor:
    name: Top floor
    entities:
        - switch.window_lights_upstairs
        - switch.floor_light_upstairs
        - sensor.top_floor_temp
        - sensor.top_floor_pressure

outdoor:
    name: Outdoor
    entities:
        - switch.garden_lights
        - sensor.outdoor_temp
        - sensor.outdoor_humidity

indoor_lights:
    name: Indoor lights
    entities:
        - switch.window_lights_downstairs
        - switch.wall_lights_downstairs
        - switch.window_lights_upstairs
        - switch.floor_light_upstairs

window_lights:
    name: Window lights
    entities:
        - switch.window_lights_downstairs
        - switch.window_lights_upstairs
    
weather_and_sun:
    name: Weather and sun
    entities:
        - sun.sun
        - sensor.yr_symbol

#family:
#    name: Family
#    entities:
#        - device_tracker.owntracks_lars

garage_group:
    name: Garage
    entities:
        - sensor.garage_temp
        - sensor.garage_humidity
        - switch.dehumidifier

automation_garden_group:
    name: automation_garden
    entities:
        - automation.turn_on_garden_lights_when_sun_sets
        - automation.turn_off_garden_lights_when_sun_rises

automation_indoor_group:
    name: automation_indoor
    entities:
        - automation.turn_on_window_lights_at_sunset
        - automation.turn_off_indoor_lights_at_night
