#
# Groups that are views
#
default_view:
    view: yes
    entities:
        - group.groundfloor
        - group.topfloor
        - group.outdoor
        - group.weather_and_sun
        - group.family
        - sensor.door_last_opened
        - group.tracker_group

garage:
    view: yes
    entities:
        - group.garage_group

cams:
    view: yes
    entities:
        - camera.outdoor1
        - camera.outdoor2
        - camera.rpi

computers_stat:
    view: yes
    entities:
        - group.raspberrypi3_group
        - group.raspberrypi2_group

automation:
    view: yes
    entities:
        - group.automation_garden_group
        - group.automation_indoor_group

media:
    view: yes
    entities:
        - media_player.kitchen
        - media_player.vardagsrum
        - media_player.sovrum
        - media_player.squeezebox

laundry:
    view: yes
    entities:
        - group.laundry_room
#
# Groups that are not views
#
laundry_room:
    name: Laundry room
    entities:
        - sensor.water_flooding
        - sensor.laundry_temp
        - sensor.laundry_humidity

groundfloor:
    name: Ground floor
    entities:
        - switch.window_lights_downstairs
        - switch.wall_lights_downstairs
        - sensor.ground_floor_temp
        - sensor.ground_floor_humidity
        - sensor.door_last_opened

topfloor:
    name: Top floor
    entities:
        - switch.window_lights_upstairs
        - switch.floor_light_upstairs
        - sensor.top_floor_temp
        - sensor.top_floor_pressure

outdoor:
    name: Outdoor
    entities:
        - switch.garden_lights
        - sensor.garden_temp
        - sensor.outdoor_temp
        - sensor.outdoor_humidity

indoor_lights:
    name: Indoor lights
    entities:
        - switch.window_lights_downstairs
        - switch.wall_lights_downstairs
        - switch.window_lights_upstairs
        - switch.floor_light_upstairs

window_lights:
    name: Window lights
    entities:
        - switch.window_lights_downstairs
        - switch.window_lights_upstairs
    
weather_and_sun:
    name: Weather and sun
    entities:
        - sensor.date__time
        - sensor.day_night
        - sensor.sunset
        - sensor.sunrise
        - sensor.yr_symbol
        - sensor.yr_pressure
        - sensor.yr_temperature
        - sensor.yr_wind_speed
        - sensor.yr_wind_direction
        - sensor.yr_cloudiness

#family:
#    name: Family
#    entities:
#        - device_tracker.owntracks_lars

garage_group:
    name: Garage
    entities:
        - sensor.garage_temp
        - sensor.garage_humidity
        - switch.dehumidifier

automation_garden_group:
    name: automation_garden
    entities:
        - automation.turn_on_garden_lights_when_sun_sets
        - automation.turn_off_garden_lights_when_sun_rises

automation_indoor_group:
    name: automation_indoor
    entities:
        - automation.turn_on_window_lights_at_sunset
        - automation.turn_off_indoor_lights_at_night

raspberrypi3_group:
    name: Raspberry Pi 3
    entities:
        - sensor.rpi3_temperature

raspberrypi2_group:
    name: Raspberry Pi 2
    entities:
        - sensor.rpi2_temperature
        - sensor.cpu_use
        - sensor.ram_free
        - sensor.disk_use_

tracker_group:
    name: Tracker group
    entities:
        - device_tracker.user_iphone
        - device_tracker.lars_nexus


