#
# Groups that are views
#
default_view:
    view: yes
    entities:
        - group.groundfloor
        - group.topfloor
        - group.outdoor
        - sun.sun
        - sensor.yr_symbol
        - device_tracker.larsiphone

garage:
    view: yes
    entities:
        - sensor.garage_temp
        - sensor.garage_humidity
        - switch.dehumidifier

cams:
    view: yes
    entities:
        - camera.outdoor
        - camera.rpi

automation:
    view: yes
    entities:
        - automation.turn_on_garden_lights_when_sun_sets
        - automation.turn_off_garden_lights_when_sun_rises

#
# Groups that are not views
#
groundfloor:
    name: Ground floor
    entities:
        - switch.window_lights_downstairs
        - switch.wall_lights_downstairs
        - sensor.ground_floor_temp
        - sensor.ground_floor_humidity

topfloor:
    name: Top floor
    entities:
        - switch.window_lights_upstairs
        - switch.floor_light_upstairs
        - sensor.top_floor_temp
        - sensor.top_floor_pressure

outdoor:
    name: Outdoor
    entities:
        - switch.garden_lights
        - sensor.outdoor_temp
        - sensor.outdoor_humidity
