# climate sensors
- platform: mqtt
  state_topic: "Home/GroundFloor/Temperature"
  name: ground_floor_temp
  unit_of_measurement: "C"
- platform: mqtt
  state_topic: "Home/GroundFloor/Humidity"
  name: ground_floor_humidity
  unit_of_measurement: "%"
- platform: mqtt
  state_topic: "Home/Outdoor/Temperature"
  name: outdoor_temp
  unit_of_measurement: "C"
- platform: mqtt
  state_topic: "Home/Outdoor/Humidity"
  name: outdoor_humidity
  unit_of_measurement: "%"
- platform: mqtt
  state_topic: "Home/TopFloor/Temperature"
  name: top_floor_temp
  unit_of_measurement: "C"
- platform: mqtt
  state_topic: "Home/TopFloor/Pressure"
  name: top_floor_pressure
  unit_of_measurement: "hPa"
- platform: mqtt
  state_topic: "Home/Garage/Temperature"
  name: garage_temp
  unit_of_measurement: "C"
- platform: mqtt
  state_topic: "Home/Garage/Humidity"
  name: garage_humidity
  unit_of_measurement: "%"

# computer sensors
- platform: mqtt
  state_topic: "Home/RPI3/Temp"
  name: rpi3_temperature
  unit_of_measurement: "C"
- platform: mqtt
  state_topic: "Home2/RPI2/Temp"
  name: rpi2_temperature
  unit_of_measurement: "C"
- platform: systemmonitor
  name: system
  resources:
    - type: processor_use
    - type: memory_free
    - type: disk_use_percent
      arg: '/'

