# climate sensors
- platform: mqtt
  state_topic: "Home/GroundFloor/Temperature"
  name: ground_floor_temp
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: "Home/GroundFloor/Humidity"
  name: ground_floor_humidity
  unit_of_measurement: "%"
- platform: mqtt
  state_topic: "Home/Outdoor/Temperature"
  name: outdoor_temp
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: "Home/Outdoor/Humidity"
  name: outdoor_humidity
  unit_of_measurement: "%"
- platform: mqtt
  state_topic: "Home/TopFloor/Temperature"
  name: top_floor_temp
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: "Home/TopFloor/Pressure"
  name: top_floor_pressure
  unit_of_measurement: "hPa"
- platform: mqtt
  state_topic: "Home/Garage/Temperature"
  name: garage_temp
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: "Home/Garage/Humidity"
  name: garage_humidity
  unit_of_measurement: "%"
- platform: mqtt
  state_topic: "Home/FrontDoor/Status"
  name: front_door_opened
- platform: mqtt
  state_topic: "Home2/Laundry/Temperature"
  name: laundry_temp
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: "Home2/Laundry/Humidity"
  name: laundry_humidity
  unit_of_measurement: "%"

# z-wave sensor values via z-way
#- platform: mqtt
#  state_topic: "zway/Laundry/Temperature"
#  name: laundry_temperature
#  unit_of_measurement: "°C"
#- platform: mqtt
#  state_topic: "zway/Laundry/Tamper"
#  name: laundry_tamper
- platform: mqtt
  state_topic: "zway/Laundry/Water"
  name: laundry_water

# computer sensors
- platform: mqtt
  state_topic: "Home/RPI3/Temp"
  name: rpi3_temperature
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: "Home/RPI2/Temp"
  name: rpi2_temperature
  unit_of_measurement: "°C"
- platform: systemmonitor
  name: system
  resources:
    - type: processor_use
    - type: memory_free
    - type: disk_use_percent
      arg: '/'


- platform: time_date
  display_options:
    - 'date_time'

- platform: template
  sensors:
    door_last_opened:
      friendly_name: 'Door last opened'
      icon_template: mdi:glassdoor
      value_template: '{{ as_timestamp(states.sensor.front_door_opened.last_updated) | timestamp_custom("%a %H:%M", True) }}'
    day_night:
      friendly_name: 'Day/Night'
      value_template: '{% if is_state("sun.sun", "above_horizon") %}Day{% else %}Night{% endif %}'
      icon_template: '{% if is_state("sun.sun", "above_horizon") %}mdi:weather-sunny{% else %}mdi:weather-night{% endif %}'
    sunset:
      friendly_name: 'Next sunset'
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%a %H:%M", True) }}'
      icon_template: mdi:weather-sunset-down
    sunrise:
      friendly_name: 'Next sunrise'
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%a %H:%M", True) }}'
      icon_template: mdi:weather-sunset-up
    water_flooding:
      value_template: '{% if is_state("sensor.laundry_water", "on") %}--- !!!FLOODING!!! ---{% else %}Relax, no problem!{% endif %}'
      icon_template: '{% if is_state("sensor.laundry_water", "on") %}mdi:alert{% else %}mdi:emoticon-cool{% endif %}'
      friendly_name: 'Flood status'
