- platform: rest
  name: window_lights_upstairs
  resource: http://192.168.1.16:5000/Outlets/api/outlets/1/1
  body_on: 'on'
  body_off: 'off'
- platform: rest
  name: floor_light_upstairs
  resource: http://192.168.1.16:5000/Outlets/api/outlets/1/4
  body_on: 'on'
  body_off: 'off'
- platform: rest
  name: window_lights_downstairs
  resource: http://192.168.1.16:5000/Outlets/api/outlets/1/2
  body_on: 'on'
  body_off: 'off'
- platform: rest
  name: wall_lights_downstairs
  resource: http://192.168.1.16:5000/Outlets/api/outlets/1/3
  body_on: 'on'
  body_off: 'off'
- platform: rest
  name: garden_lights
  resource: http://192.168.1.16:5000/Outlets/api/outlets/2/1
  body_on: 'on'
  body_off: 'off'
- platform: rest
  name: dehumidifier
  resource: http://192.168.1.16:5000/Outlets/api/outlets/2/2
  body_on: 'on'
  body_off: 'off'
